# Generated by Django 2.0.3 on 2018-03-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('url', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=32)),
            ],
        ),
    ]
