<?php
echo "\n";
echo "<!DOCTYPE html>\n";
echo "<html lang=\"en\">\n";
echo "\n";
echo "    <head>\n";
echo "        <meta charset=\"utf-8\">\n";
echo "        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n";
echo "        <meta name=\"description\" content=\"Course Hero Unlock | Chegg Unmask\">\n";
echo "        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
echo "        <title>CourseHero Unlock</title>\n";
echo "\n";
echo "        <!-- CSS -->\n";
echo "        <link rel=\"stylesheet\" href=\"http://fonts.googleapis.com/css?family=Roboto:400,100,300,500\">\n";
echo "        <link rel=\"stylesheet\" href=\"/statics/assets/bootstrap/css/bootstrap.min.css\">\n";
echo "        <link rel=\"stylesheet\" href=\"/statics/assets/font-awesome/css/font-awesome.min.css\">\n";
echo "        <link rel=\"stylesheet\" href=\"/statics/assets/css/form-elements.css\">\n";
echo "        <link rel=\"stylesheet\" href=\"/statics/assets/css/style.css\">\n";
echo "\n";
echo "        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\n";
echo "        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n";
echo "        <!--[if lt IE 9]>\n";
echo "            <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\n";
echo "            <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\n";
echo "        <![endif]-->\n";
echo "\n";
echo "        <!-- Favicon and touch icons -->\n";
echo "        <!--\n";
echo "        <link rel=\"shortcut icon\" href=\"/statics/assets/ico/favicon.png\">\n";
echo "        <link rel=\"apple-touch-icon-precomposed\" sizes=\"144x144\" href=\"/statics/assets/ico/apple-touch-icon-144-precomposed.png\">\n";
echo "        <link rel=\"apple-touch-icon-precomposed\" sizes=\"114x114\" href=\"/statics/assets/ico/apple-touch-icon-114-precomposed.png\">\n";
echo "        <link rel=\"apple-touch-icon-precomposed\" sizes=\"72x72\" href=\"/statics/assets/ico/apple-touch-icon-72-precomposed.png\">\n";
echo "        <link rel=\"apple-touch-icon-precomposed\" href=\"/statics/assets/ico/apple-touch-icon-57-precomposed.png\">\n";
echo "    -->\n";
echo "        <style>\n";
echo "            #instr {\n";
echo "                text-decoration: underline;\n";
echo "            }\n";
echo "        </style>\n";
echo "    </head>\n";
echo "\n";
echo "    <body>\n";
echo "\n";
echo "    <!-- Top content -->\n";
echo "            <!--           \n";
echo "            <div class=\"container\"> \n";
echo "                <div class=\"row\"> \n";
echo "                    <div class=\"col-sm-12 col-md-6 col-lg-8\"> \n";
echo "                        <div class=\"banner-text-inner\"> \n";
echo "                            <h1>郭媒体 GUO.MEDIA</h1> <h2>一切都是刚刚开始 \n";
echo "                                <i class=\"fa fa-hand-grab-o\" aria-hidden=\"true\"></i> <i class=\"fa fa-hand-grab-o\" aria-hidden=\"true\"></i> <i class=\"fa fa-hand-grab-o\" aria-hidden=\"true\"></i> !</h2> <p>郭媒体GUO.MEDIA 现正推出试行版，希望各位好友多多支持，提供建议给我们完善平台。我们致力提供一个自由的社交直播平台，让大家随意表达不同意见。</p> \n";
echo "                        </div> \n";
echo "                        <div class=\"login_footer\"> \n";
echo "                            <div class=\"container\"> \n";
echo "                                <div class=\"row footer\"> \n";
echo "                                    <div class=\"col-lg-6 col-md-6 col-sm-6\"> © 2018 郭媒体 GUO.MEDIA · <span class=\"text-link\" data-toggle=\"modal\" data-url=\"#translator\"><span class=\"flag-icon flag-icon-cn\"></span>&nbsp;简体中文</span> </div> <div class=\"col-lg-6 col-md-6 col-sm-6 links\"> \n";
echo "                                        <a href=\"https://www.guo.media/static/about\"> 关于我们 </a> ·                                  \n";
echo "                                        <a href=\"https://www.guo.media/static/terms\"> 条款 </a> ·                                  \n";
echo "                                        <a href=\"https://www.guo.media/static/privacy\"> 隐私 </a> · \n";
echo "                                        <a href=\"https://www.guo.media/contacts\"> 联络我们 </a> \n";
echo "                                    </div> \n";
echo "                                </div> \n";
echo "                            </div> \n";
echo "                        </div> \n";
echo "                    </div> \n";
echo "            >\n";
echo "    -->\n";
echo "    <div class=\"top-content\">\n";
echo "\n";
echo "        <div class=\"inner-bg\">\n";
echo "            <div class=\"container\">\n";
echo "                <!-- title -->\n";
echo "                <div class=\"row\">\n";
echo "                    <div class=\"col-sm-8 col-sm-offset-2 text\">\n";
echo "                      <font size = \"12\" color = \"white\" face = \"Times\"> <strong>Chegg Hero</strong></font>\n";
echo "                      <div class=\"description\">\n";
echo "                      </div>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "                <!-- 欢迎语 -->\n";
echo "                <div class=\"row\">\n";
echo "                    <div class=\"col-sm-10 col-sm-offset-1 form-box\">\n";
echo "                        <!-- top -->\n";
echo "                        <div class=\"form-top\">\n";
echo "        \n";
echo "                            <div class=\"form-top-left\">\n";
echo "\n";
echo "                                <h3 id=\"t5\">CheggHero文件解锁系统现正推行内测版<!--(维护中)--></h3>\n";
echo "                                <p id=\"t4\">我们致力用最快的速度为您自动解锁 CouseHero 上的任何文档, 内测期间您只需支付1元即可解锁指定文件</p>\n";
echo "                                <!--<p> <a style=\"color:beige\" href=\"https://youtu.be/v5lsD-1CIcM\" id=\"instr\">[视频操作指南]</a></p>-->\n";
echo "                            </div>\n";
echo "\n";
echo "                        </div>\n";
echo "\n";
echo "                        <!-- bottom -->\n";
echo "                        <div class=\"form-bottom\">\n";
echo "\n";
echo "                            <form role=\"form\" action=\"/unlock\" method=\"get\" class=\"login-form\" enctype=\"multipart/form-data\">\n";
echo "                                <!-- 兑换码 -->\n";
echo "                                <div class=\"form-group\" id=\"t1\">\n";
echo "                                    <label class=\"sr-only\" for=\"form-password\">兑换码</label>\n";
echo "                                  <input type=\"text\" name=\"code\" placeholder=\"兑换码\" class=\"form-password form-control\" id=\"form-password\">\n";
echo "                                </div>\n";
echo "                                <!-- 网址 -->\n";
echo "                                <div class=\"form-group\" id=\"t2\">\n";
echo "                                    <label class=\"sr-only\" for=\"form-username\">网址</label>\n";
echo "                                    <input type=\"text\" name=\"url\" placeholder=\"CourseHero文件网址\" class=\"form-username form-control\" id=\"form-username\">\n";
echo "                                </div>\n";
echo "                                <!-- 邮箱 -->\n";
echo "                                <div class=\"form-group\" id=\"t3\">\n";
echo "                                    <label class=\"sr-only\" for=\"form-password\">邮箱</label>\n";
echo "                                    <input type=\"text\" name=\"email\" placeholder=\"输入您的邮箱\" class=\"form-email form-control\" id=\"form-email\">\n";
echo "                                </div>\n";
echo "                                <!-- submit -->\n";
echo "                                <button type=\"submit\" class=\"btn\" onclick=\"myFunction()\" id=\"tt\">Unlock File</button>\n";
echo "                                <!-- description -->\n";
echo "                                <div class=\"description\">\n";
echo "                                <p ><a id=\"60s\" style=\"display:none\">\n";
echo "                                    <strong> File unlocking. About 60 seconds. Please check your email. Please contact us if you have any problem.</strong></a></p>\n";
echo "                                </div>\n";
echo "\n";
echo "                            </form>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "                <!-- 底部 -->\n";
echo "                <div class=\"row\">\n";
echo "                    <div class=\"col-sm-8 col-sm-offset-2 social-login\">\n";
echo "                        <!-- button -->\n";
echo "                        <div class=\"social-login-buttons\">\n";
echo "                            <!--\n";
echo "                            <a class=\"btn btn-link-2\" id=\"bt1\" onClick=\"window.open('https://item.taobao.com/item.htm?id=541676859032')\"> 获取兑换码 </a>\n";
echo "                            -->\n";
echo "                            <a class=\"btn btn-link-2\" id=\"bt2\" onClick=\"window.open('http://www.zuopay.com/details/1BFD17E977E53DFA')\"> 支付宝微信扫码1元获取兑换码</a>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "                <!-- foottage -->\n";
echo "                <div class=\"login_footer\"> \n";
echo "                    <div class=\"container\"> \n";
echo "                        <div class=\"row footer\"> \n";
echo "                            <div class=\"col-sm-8 col-sm-offset-2\">\n";
echo "                                <font size = \"3\" color = \"white\">© 2018 CheggHero www.chegghero.com ·</font>\n";
echo "                                <!-- title -->\n";
echo "                                <font size = \"3\" color = \"white\">Redifining the future of Course Hero unlock services ·</font>\n";
echo "                                <a href=\"mailto:chegghero@hotmail.com\"> <font size = \"3\" color = \"Lime\"> <strong>联系我们</strong> ·</font> </a> \n";
echo "                            </div> \n";
echo "                        </div> \n";
echo "                    </div> \n";
echo "                </div>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "    </div>\n";
echo "\n";
echo "    <!-- Javascript -->\n";
echo "    <script src=\"/statics/assets/js/jquery-1.11.1.min.js\"></script>\n";
echo "    <script src=\"/statics/assets/bootstrap/js/bootstrap.min.js\"></script>\n";
echo "    <script src=\"/statics/assets/js/jquery.backstretch.min.js\"></script>\n";
echo "    <script src=\"/statics/assets/js/scripts.js\"></script>\n";
echo "    <script>\n";
echo "\n";
echo "        function myFunction() {\n";
echo "\n";
echo "            var change = document.getElementById(\"tt\");\n";
echo "            var change1 = document.getElementById(\"t1\");\n";
echo "            var change2 = document.getElementById(\"t2\");\n";
echo "            var change3 = document.getElementById(\"t3\");\n";
echo "            var ch = document.getElementById(\"60s\");\n";
echo "\n";
echo "            if (change.innerHTML === \"Unlock File\")\n";
echo "            {\n";
echo "                //window.open('/s', '_blank');\n";
echo "                change.innerHTML = \"Unlock Again\";\n";
echo "                change.style.display = \"none\";\n";
echo "                change1.style.display = \"none\";\n";
echo "                change2.style.display = \"none\";\n";
echo "                change3.style.display = \"none\";\n";
echo "\n";
echo "            }\n";
echo "            else {\n";
echo "                //window.open('/s', '_blank');\n";
echo "                change.innerHTML = \"Unlock File\";\n";
echo "                change.style.display = \"none\";\n";
echo "                change1.style.display = \"none\";\n";
echo "                change2.style.display = \"none\";\n";
echo "                change3.style.display = \"none\";\n";
echo "\n";
echo "            }\n";
echo "            ch.style.display = \"block\";\n";
echo "            setTimeout(function(){ change.style.display = \"block\"}, 15000);\n";
echo "            setTimeout(function(){ change1.style.display = \"block\"}, 15000);\n";
echo "            setTimeout(function(){ change2.style.display = \"block\"}, 15000);\n";
echo "            setTimeout(function(){ change3.style.display = \"block\"}, 15000);\n";
echo "            setTimeout(function(){ ch.style.display = \"none\"}, 15000);\n";
echo "        }\n";
echo "\n";
echo "        function myFunction2() {\n";
echo "\n";
echo "            var change = document.getElementById(\"tt\");\n";
echo "            change.style.display = \"block\";\n";
echo "        }\n";
echo "    </script>\n";
echo "    \n";
echo "    </body>\n";
echo "\n";
echo "</html>";
?>